import { getToken,getRefreshToken,getTokenTime } from '@/utils/auth'

export default {
  user: '',
  status: '',
  code: '',
  token: getToken(),
  tokenTime: getTokenTime(),
  refreshToken: getRefreshToken(),
  name: '',
  avatar: '',
  introduction: '',
  permissions:[],
  /*permissions:[
    {
      "id": 5541,
      "resourceName": "用户服务11111",
      "resourceCode": "0",
      "parentId": 0,
      "resourceType": "getway_user",
      "resourceUrl": "/user",
      "description": "用户服务",
      "dataStatus": 0
    },
    {
      "id": 1,
      "resourceName": "用户服务",
      "resourceCode": "0",
      "parentId": 0,
      "resourceType": "getway_user",
      "resourceUrl": "/user",
      "description": "用户服务",
      "dataStatus": 0
    }, {
      "id": 2,
      "resourceName": "登录管理",
      "resourceCode": "2",
      "parentId": 0,
      "resourceType": "login",
      "resourceUrl": "/login",
      "description": "登录管理",
      "dataStatus": 0
    }, {
      "id": 3,
      "resourceName": "日志服务",
      "resourceCode": "3",
      "parentId": 0,
      "resourceType": "logs",
      "resourceUrl": "/logs",
      "description": "日志服务",
      "dataStatus": 0
    }, {
      "id": 147,
      "resourceName": "用户管理",
      "resourceCode": "1.1",
      "parentId": 1,
      "resourceType": "user_user",
      "resourceUrl": "/user/user",
      "description": "用户管理",
      "dataStatus": 0
    }, {
      "id": 149,
      "resourceName": "用户登录",
      "resourceCode": "2.1",
      "parentId": 2,
      "resourceType": "login_auth",
      "resourceUrl": "/login/auth",
      "description": "用户登录",
      "dataStatus": 0
    }, {
      "id": 150,
      "resourceName": "获取用户数据",
      "resourceCode": "1.4.8",
      "parentId": 1479,
      "resourceType": "user_userext_queryData",
      "resourceUrl": "/user/userext/queryData",
      "description": "获取用户数据",
      "dataStatus": 0
    }, {
      "id": 151,
      "resourceName": "查询用户状态类型列表",
      "resourceCode": "1.4.9",
      "parentId": 1479,
      "resourceType": "user_userext_queryUserStateinfo",
      "resourceUrl": "/user/userext/queryUserStateinfo",
      "description": "查询用户状态类型列表",
      "dataStatus": 0
    }, {
      "id": 152,
      "resourceName": "查询用户类型列表",
      "resourceCode": "1.4.10",
      "parentId": 1479,
      "resourceType": "user_userext_queryUserTypeinfo",
      "resourceUrl": "/user/userext/queryUserTypeinfo",
      "description": "查询用户类型列表",
      "dataStatus": 0
    }, {
      "id": 153,
      "resourceName": "添加用户",
      "resourceCode": "1.4.11",
      "parentId": 1479,
      "resourceType": "user_userext_addUser",
      "resourceUrl": "/user/userext/addUser",
      "description": "添加用户",
      "dataStatus": 0
    }, {
      "id": 154,
      "resourceName": "修改用户",
      "resourceCode": "1.4.12",
      "parentId": 1479,
      "resourceType": "user_userext_updateUser",
      "resourceUrl": "/user/userext/updateUser",
      "description": "修改用户",
      "dataStatus": 0
    }, {
      "id": 155,
      "resourceName": "删除用户",
      "resourceCode": "1.4.13",
      "parentId": 1479,
      "resourceType": "user_userext_dele",
      "resourceUrl": "/user/userext/dele",
      "description": "删除用户",
      "dataStatus": 0
    }, {
      "id": 156,
      "resourceName": "重置用户密码",
      "resourceCode": "1.4.14",
      "parentId": 1479,
      "resourceType": "user_userext_resetPwd",
      "resourceUrl": "/user/userext/resetPwd",
      "description": "重置用户密码",
      "dataStatus": 0
    }, {
      "id": 157,
      "resourceName": "修改用户密码",
      "resourceCode": "1.4.15",
      "parentId": 1479,
      "resourceType": "user_userext_updatePwd",
      "resourceUrl": "/user/userext/updatePwd",
      "description": "修改用户密码",
      "dataStatus": 0
    }, {
      "id": 158,
      "resourceName": "部门管理",
      "resourceCode": "1.2",
      "parentId": 1,
      "resourceType": "user_dept",
      "resourceUrl": "/user/dept",
      "description": "部门管理",
      "dataStatus": 0
    }, {
      "id": 159,
      "resourceName": "部门查询-分页",
      "resourceCode": "1.2.1",
      "parentId": 158,
      "resourceType": "user_dept_queryAllUsableDeptInfo",
      "resourceUrl": "/user/dept/queryAllUsableDeptInfo",
      "description": "部门查询-分页",
      "dataStatus": 0
    }, {
      "id": 161,
      "resourceName": "添加部门",
      "resourceCode": "1.2.3",
      "parentId": 158,
      "resourceType": "user_dept_addDept",
      "resourceUrl": "/user/dept/addDept",
      "description": "添加部门",
      "dataStatus": 0
    }, {
      "id": 162,
      "resourceName": "单位类型查询",
      "resourceCode": "1.2.4",
      "parentId": 158,
      "resourceType": "user_dept_queryDeptType",
      "resourceUrl": "/user/dept/queryDeptType",
      "description": "单位类型查询",
      "dataStatus": 0
    }, {
      "id": 163,
      "resourceName": "修改部门信息",
      "resourceCode": "1.2.5",
      "parentId": 158,
      "resourceType": "user_dept_updateDeptInfo",
      "resourceUrl": "/user/dept/updateDeptInfo",
      "description": "修改部门信息",
      "dataStatus": 0
    }, {
      "id": 164,
      "resourceName": "删除部门",
      "resourceCode": "1.2.6",
      "parentId": 158,
      "resourceType": "user_dept_deleteDept",
      "resourceUrl": "/user/dept/deleteDept",
      "description": "删除部门",
      "dataStatus": 0
    }, {
      "id": 165,
      "resourceName": "部门CSV导入",
      "resourceCode": "1.2.7",
      "parentId": 158,
      "resourceType": "user_dept_ajaxUpload",
      "resourceUrl": "/user/dept/ajaxUpload",
      "description": "部门CSV导入",
      "dataStatus": 0
    }, {
      "id": 166,
      "resourceName": "部门CSV导出",
      "resourceCode": "1.2.8",
      "parentId": 158,
      "resourceType": "user_dept_downCsv",
      "resourceUrl": "/user/dept/downCsv",
      "description": "部门CSV导处",
      "dataStatus": 0
    }, {
      "id": 167,
      "resourceName": "部门查询-不分页",
      "resourceCode": "1.2.2",
      "parentId": 158,
      "resourceType": "user_dept_queryAllDept",
      "resourceUrl": "/user/dept/queryAllDept",
      "description": "部门查询-不分页",
      "dataStatus": 0
    }, {
      "id": 170,
      "resourceName": "角色管理",
      "resourceCode": "1.3",
      "parentId": 1,
      "resourceType": "user_role",
      "resourceUrl": "/user/role",
      "description": "角色管理",
      "dataStatus": 0
    }, {
      "id": 171,
      "resourceName": "查询角色数据-分页",
      "resourceCode": "1.3.1",
      "parentId": 170,
      "resourceType": "user_role_queryPage",
      "resourceUrl": "/user/role/queryPage",
      "description": "查询角色数据-分页",
      "dataStatus": 0
    }, {
      "id": 172,
      "resourceName": "添加角色",
      "resourceCode": "1.3.2",
      "parentId": 170,
      "resourceType": "user_role_addRole",
      "resourceUrl": "/user/role/addRole",
      "description": "添加角色",
      "dataStatus": 0
    }, {
      "id": 173,
      "resourceName": "修改角色",
      "resourceCode": "1.3.3",
      "parentId": 170,
      "resourceType": "user_role_updateRole",
      "resourceUrl": "/user/role/updateRole",
      "description": "修改角色",
      "dataStatus": 0
    }, {
      "id": 1473,
      "resourceName": "删除角色",
      "resourceCode": "1.3.4",
      "parentId": 170,
      "resourceType": "user_role_dele",
      "resourceUrl": "/user/role/dele",
      "description": "删除角色",
      "dataStatus": 0
    }, {
      "id": 1474,
      "resourceName": "刷新Token",
      "resourceCode": "2.1",
      "parentId": 2,
      "resourceType": "login_refreshAuthorization",
      "resourceUrl": "/login/refreshAuthorization",
      "description": "刷新Token",
      "dataStatus": 0
    }, {
      "id": 1475,
      "resourceName": "角色资源设置",
      "resourceCode": "1.3.5",
      "parentId": 170,
      "resourceType": "user_role_setRoleResource",
      "resourceUrl": "/user/role/setRoleResource",
      "description": "角色资源设置",
      "dataStatus": 0
    }, {
      "id": 1476,
      "resourceName": "添加日志",
      "resourceCode": "3.1",
      "parentId": 3,
      "resourceType": "logs_add",
      "resourceUrl": "/logs/add",
      "description": "添加日志",
      "dataStatus": 0
    }, {
      "id": 1477,
      "resourceName": "查询日志",
      "resourceCode": "3.2",
      "parentId": 3,
      "resourceType": "logs_select",
      "resourceUrl": "/logs/select",
      "description": "查询日志",
      "dataStatus": 0
    }, {
      "id": 1478,
      "resourceName": "根据角色id查询资源",
      "resourceCode": "1.3.6",
      "parentId": 170,
      "resourceType": "user_role_queryResource",
      "resourceUrl": "/user/role/queryResource",
      "description": "根据角色id查询资源",
      "dataStatus": 0
    }, {
      "id": 1479,
      "resourceName": "用户信息管理",
      "resourceCode": "1.4",
      "parentId": 1,
      "resourceType": "user_userext",
      "resourceUrl": "/user/userext",
      "description": "用户信息管理",
      "dataStatus": 0
    }, {
      "id": 1480,
      "resourceName": "查询权限下所有人员列表",
      "resourceCode": "1.4.1",
      "parentId": 1479,
      "resourceType": "user_userext_queryUserExtByRoleId",
      "resourceUrl": "/user/userext/queryUserExtByRoleId",
      "description": "查询权限下所有人员列表",
      "dataStatus": 0
    }, {
      "id": 1481,
      "resourceName": "查看人员列表",
      "resourceCode": "1.4.2",
      "parentId": 1479,
      "resourceType": "user_userext_queryUserExt",
      "resourceUrl": "/user/userext/queryUserExt",
      "description": "查看人员列表",
      "dataStatus": 0
    }, {
      "id": 1482,
      "resourceName": "修改人员信息",
      "resourceCode": "1.4.3",
      "parentId": 1479,
      "resourceType": "user_userext_updatePeopleInfo",
      "resourceUrl": "/user/userext/updatePeopleInfo",
      "description": "修改人员信息",
      "dataStatus": 0
    }, {
      "id": 1483,
      "resourceName": "添加人员和信息",
      "resourceCode": "1.4.4",
      "parentId": 1479,
      "resourceType": "user_userext_addPeopleInfo",
      "resourceUrl": "/user/userext/addPeopleInfo",
      "description": "添加人员和信息",
      "dataStatus": 0
    }, {
      "id": 1484,
      "resourceName": "删除人员",
      "resourceCode": "1.4.5",
      "parentId": 1479,
      "resourceType": "user_userext_deletePeopleInfo",
      "resourceUrl": "/user/userext/deletePeopleInfo",
      "description": "删除人员",
      "dataStatus": 0
    }, {
      "id": 1485,
      "resourceName": "人员CSV导入",
      "resourceCode": "1.4.6",
      "parentId": 1479,
      "resourceType": "user_userext_ajaxUpload",
      "resourceUrl": "/user/userext/ajaxUpload",
      "description": "人员CSV导入",
      "dataStatus": 0
    }, {
      "id": 1486,
      "resourceName": "人员CSV导出",
      "resourceCode": "1.4.7",
      "parentId": 1479,
      "resourceType": "user_userext_downotherCsv",
      "resourceUrl": "/user/userext/downotherCsv",
      "description": "人员CSV导出",
      "dataStatus": 0
    }, {
      "id": 1487,
      "resourceName": "资源权限管理",
      "resourceCode": "1.5",
      "parentId": 1,
      "resourceType": "user_resource",
      "resourceUrl": "/user/resource",
      "description": "资源权限管理",
      "dataStatus": 0
    }, {
      "id": 1488,
      "resourceName": "添加资源权限",
      "resourceCode": "1.5.1",
      "parentId": 1487,
      "resourceType": "user_resource_addResource",
      "resourceUrl": "/user/resource/addResource",
      "description": "添加资源权限",
      "dataStatus": 0
    }, {
      "id": 1489,
      "resourceName": "删除资源权限",
      "resourceCode": "1.5.2",
      "parentId": 1487,
      "resourceType": "user_resource_del",
      "resourceUrl": "/user/resource/del",
      "description": "删除资源权限",
      "dataStatus": 0
    }, {
      "id": 1490,
      "resourceName": "根据账户查询获取人员信息",
      "resourceCode": "1.4.16",
      "parentId": 1479,
      "resourceType": "user_userext_queryUserExtByAccount",
      "resourceUrl": "/user/userext/queryUserExtByAccount",
      "description": "根据账户查询获取人员信息",
      "dataStatus": 0
    }, {
      "id": 1491,
      "resourceName": "获取当前用户资源信息",
      "resourceCode": "1.5.3",
      "parentId": 1487,
      "resourceType": "user_resource_findByThisUser",
      "resourceUrl": "/user/resource/findByThisUser",
      "description": "获取当前用户资源信息",
      "dataStatus": 0
    }, {
      "id": 1492,
      "resourceName": "获取资源信息根据userId",
      "resourceCode": "1.5.4",
      "parentId": 1487,
      "resourceType": "user_resource_findByUserId",
      "resourceUrl": "/user/resource/findByUserId",
      "description": "获取资源信息根据userId",
      "dataStatus": 0
    }, {
      "id": 1493,
      "resourceName": "根据Url获取资源",
      "resourceCode": "1.5.4",
      "parentId": 1487,
      "resourceType": "user_resource_findByUrl",
      "resourceUrl": "/user/resource/findByUrl",
      "description": "根据Url获取资源",
      "dataStatus": 0
    }, {
      "id": 1494,
      "resourceName": "组织机构操作",
      "resourceCode": "1.6",
      "parentId": 1,
      "resourceType": "user_organization",
      "resourceUrl": "/user/organization",
      "description": "组织机构操作",
      "dataStatus": 0
    }, {
      "id": 1495,
      "resourceName": "删除组织(多选删除)",
      "resourceCode": "1.6.1",
      "parentId": 1494,
      "resourceType": "user_organization_deletes",
      "resourceUrl": "/user/organization/deletes",
      "description": "删除组织(多选删除)",
      "dataStatus": 0
    }, {
      "id": 1496,
      "resourceName": "添加组织",
      "resourceCode": "1.6.2",
      "parentId": 1494,
      "resourceType": "user_organization_add",
      "resourceUrl": "/user/organization/add",
      "description": "添加组织",
      "dataStatus": 0
    }, {
      "id": 1497,
      "resourceName": "删除组织(单删除)",
      "resourceCode": "1.6.3",
      "parentId": 1494,
      "resourceType": "user_organization_del",
      "resourceUrl": "/user/organization/del",
      "description": "删除组织(单删除)",
      "dataStatus": 0
    }, {
      "id": 1498,
      "resourceName": "查询可用组织",
      "resourceCode": "1.6.4",
      "parentId": 1494,
      "resourceType": "user_organization_queryor",
      "resourceUrl": "/user/organization/queryor",
      "description": "查询可用组织",
      "dataStatus": 0
    }
  ],*/
  roles: [],
  setting: {
    articlePlatform: []
  }
}
